# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3959ca0d8efc3859f5fc3b10fa428276a216b1d596ae906c135d8240f3b23906728458269026a5b6685739ac84d6bcac89e08ac85d2da97fcc03caf2005b69a6

test:
  secret_key_base: a1ec933837f11a17b18c4da2d215f32cea2929cf0d6ec1b0c3eabc69e471bdf0f6e9582b4661ec3fc83107c5ca6ef06e8786a8bb6cca63b547e2fdcfe0ddc6ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
